//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



//public partial class AdminArea_Deposit {
    
    /// <summary>
    /// pnl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.Panel pnl1;
    
    /// <summary>
    /// txtname control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.TextBox txtname;
    
    /// <summary>
    /// rfvname control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvname;
    
    /// <summary>
    /// txtamount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.TextBox txtamount;
    
    /// <summary>
    /// rfvamount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvamount;
    
    /// <summary>
    /// rangedep control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.RangeValidator rangedep;
    
    /// <summary>
    /// lblerror control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.Label lblerror;
    
    /// <summary>
    /// btnsubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.Button btnsubmit;
    
    /// <summary>
    /// pnl2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
//    protected global::System.Web.UI.WebControls.Panel pnl2;
//}
